name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 10.15
      - name: Build
        run: JAVA_OPTS="-Xmx2g" sbt -v build